export const technologyIcons = {
  "React": "https://www.vectorlogo.zone/logos/reactjs/reactjs-icon.svg",
  "Node.js": "https://www.vectorlogo.zone/logos/nodejs/nodejs-icon.svg",
  "MongoDB": "https://www.vectorlogo.zone/logos/mongodb/mongodb-icon.svg",
  "Tailwind CSS": "https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg",
  "Firebase": "https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg",
  "Express": "https://www.vectorlogo.zone/logos/expressjs/expressjs-icon.svg",
  "Next.js": "https://www.vectorlogo.zone/logos/nextjs/nextjs-icon.svg",
  "Python": "https://www.vectorlogo.zone/logos/python/python-icon.svg",
  "TypeScript": "https://www.vectorlogo.zone/logos/typescriptlang/typescriptlang-icon.svg",
  "JavaScript": "https://www.vectorlogo.zone/logos/javascript/javascript-icon.svg",
  "Framer Motion": "https://www.vectorlogo.zone/logos/framer/framer-icon.svg",
  "Redux": "https://raw.githubusercontent.com/reduxjs/redux/master/logo/logo.png",
  "Prisma": "https://static-00.iconduck.com/assets.00/file-type-prisma-icon-210x256-v7xrnm1k.png",
  "PostgreSQL": "https://www.vectorlogo.zone/logos/postgresql/postgresql-icon.svg",
  "Docker": "https://www.vectorlogo.zone/logos/docker/docker-tile.svg",
  "Postman": "https://rangav.gallerycdn.vsassets.io/extensions/rangav/vscode-thunder-client/2.34.2/1740400742896/Microsoft.VisualStudio.Services.Icons.Default",
  "Figma": "https://www.vectorlogo.zone/logos/figma/figma-icon.svg",
  "Git": "https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg",
  "Cloudinary": "https://vectorwiki.com/images/AIm9a__cloudinary.svg",
  "JWT": "https://jwt.io/img/pic_logo.svg",
  "MySQL": "https://www.vectorlogo.zone/logos/mysql/mysql-icon.svg",
  "Nodemailer": "https://repository-images.githubusercontent.com/1272424/d1995000-0ab7-11ea-8ed3-04a082c36b0d",
  "Auth.js": "https://authjs.dev/img/logo-sm.png",
  "ShadCN": "https://mediaresource.sfo2.digitaloceanspaces.com/wp-content/uploads/2024/04/20161105/shadcn-ui-logo-EF735EC0E5-seeklogo.com.png"
};